# Dockerfile: iperf
# Kafouche iPerf Image (source).

ARG         RELEASE=3.19.1

ARG         SOURCE_URL=https://github.com/esnet/iperf/archive/$RELEASE.tar.gz

ARG         SOURCE_DIR=/tmp/source

ARG         SOURCE_TAR=/tmp/archive.tar.xz

ARG         TARGET_DIR=/tmp/target


# BUILD STAGE

FROM        ghcr.io/kafouche/alpine:latest as buildstage

ARG         SOURCE_DIR \
            SOURCE_TAR \
            SOURCE_URL \
            TARGET_DIR

            # MAKE PACKAGES
RUN         apk --no-cache --update upgrade \
            && apk --no-cache --update add \
              g++ \
              make

            # DOWNLOAD SOURCE
RUN         apk --no-cache --update add \
              curl \
            && curl \
              --location "${SOURCE_URL}" \
              --output "${SOURCE_TAR}" \
            && mkdir --parents "${SOURCE_DIR}" \
            && tar \
              --directory="${SOURCE_DIR}" \
              --extract \
              --file="${SOURCE_TAR}" \
              --gzip \
              --strip-components=1

WORKDIR     "${SOURCE_DIR}"

RUN         ./configure \
              --prefix=/usr \
              --sysconfdir=/etc \
              --mandir=/usr/share/man \
              --infodir=/usr/share/info \
              --disable-static \
            && make \
            && make check \
            && DESTDIR="${TARGET_DIR}" make install


# RUN STAGE

FROM        ghcr.io/kafouche/alpine:latest

LABEL       org.opencontainers.image.authors="kafouche"
LABEL       org.opencontainers.image.base.name="ghcr.io/kafouche/iperf:3.19.1"
LABEL       org.opencontainers.image.ref.name="ghcr.io/kafouche/alpine"
LABEL       org.opencontainers.image.source="https://github.com/kafouche/container-iperf"
LABEL       org.opencontainers.image.title="iPerf3"
LABEL       org.opencontainers.image.version="3.19.1"
LABEL       image.tags[0]="ghcr.io/kafouche/iperf:latest-src"

# ------------------------------------------------------------------------------

ARG         TARGET_DIR

RUN         apk --no-cache --update upgrade

COPY        --from=buildstage "${TARGET_DIR}/" /

RUN         addgroup -S iperf \
            && adduser -D -G iperf -h /var/lib/iperf -H -s /sbin/nologin -S iperf

WORKDIR     /

EXPOSE      5201

USER        iperf

ENTRYPOINT  [ "/usr/bin/iperf3" ]
CMD         [ "--server" ]
